### ISSUE TITLE
Tag 1.1.0 crashes when decoding a ROS Vector3 message

### ISSUE THREAD

**Issue by huyaoyu** [DimaRU/CDRCodable#1]
Using the latest pre-release 1.1.0 on iPhone, the App crashes when trying to decode a ROS Vector3 message. The location is https://github.com/DimaRU/CDRCodable/blob/563e7abe6cb4b5617035073582c3b71d2b469833/Sources/CDRCodable/Decoder/CDRDecoder.swift#L144 

XCode reported "Fatal error: load from misaligned raw pointer".

System:
macOS Sonoma 14.2.1
iOS SDK 17
Xcode 15.0.1

**Comment by DimaRU** [comment]
To solve the problem I need more information: swift struct definition which includes Vector3 message.

**Comment by DimaRU** [comment]
Fixed in 1.1.1 release.
